// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG3x8FoiaF-Sny8-_bEq-cS17ZtCGT-Zw',
    appId: '1:290522704139:web:84967083a75137e5ef5a0e',
    messagingSenderId: '290522704139',
    projectId: 'ta-penyakit-daun-cabai',
    authDomain: 'ta-penyakit-daun-cabai.firebaseapp.com',
    databaseURL: 'https://ta-penyakit-daun-cabai-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ta-penyakit-daun-cabai.firebasestorage.app',
    measurementId: 'G-2QKJ3930SK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcJy9GLcH93J9iHLs8Vvpr0WhvXE35Xac',
    appId: '1:290522704139:android:cbb588b695b72e51ef5a0e',
    messagingSenderId: '290522704139',
    projectId: 'ta-penyakit-daun-cabai',
    databaseURL: 'https://ta-penyakit-daun-cabai-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ta-penyakit-daun-cabai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3_DhOcmqlGtTWtQYnmICxbQyKz2aJkJ0',
    appId: '1:290522704139:ios:03d69cfdcea5a5f0ef5a0e',
    messagingSenderId: '290522704139',
    projectId: 'ta-penyakit-daun-cabai',
    databaseURL: 'https://ta-penyakit-daun-cabai-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ta-penyakit-daun-cabai.firebasestorage.app',
    iosBundleId: 'com.ta.penyakitDaun',
  );

}